name: Run Wix Scraper

on:
  push:
    branches: [ main ]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
  
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Chromium dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y libnss3 libgconf-2-4 libxss1 libasound2 libxtst6 libgtk-3-0
          sudo ln -s /usr/bin/chromium-browser /usr/bin/chromium || true


    - name: Run wixscraper
      run: python wixscraper.py
