name: Run Wix Scraper

on:
  push:
    branches: [ main ]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
   
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download Chromium for Pyppeteer
      run: |
       python -c "from pyppeteer import chromium_downloader; chromium_downloader.download_chromium()"  
        
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
        libasound2t64 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libcups2 \
        libxcomposite1 \
        libxdamage1 \
        libxrandr2 \
        libgbm1 \
        libnss3 \
        libxss1 \
        libxshmfence1 \
        fonts-liberation \
        libappindicator3-1 \
        xdg-utils


    - name: Run wixscraper
      run: python wixscraper.py
